app/auth.py
from flask import Blueprint, render_template, flash, redirect, sessions, url_for , session
from wtforms.validators import ValidationError
from app.db import createUser

from app.forms import *
from .helpers import *

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
  print("in the login function")
  print(' here>>>>>>>>>>>>>>>>>>>>>>', type(session))
  form = LoginForm('customer')
  if form.validate_on_submit():                             #validate and check for the right credentials                                                               
    hash_to_check = fetch_user_hash(form.email.data, 'customer')        #fetch the hash related to the email (correct password)
    if check_hash(hash_to_check, form.password.data):
      flash('You are Logged in', category='success')
      create_user_session(form.email.data, 'customer')
      print('form object hereeeeeeeeeeeeeeeeeeeeeeeeeee', session)
      # return  redirect(url_for('auth.profile_page', user_session=user_session))
      return  redirect(url_for('auth.profile_page'))
    else:
      flash('Wrong Credential!', category='danger')
      return redirect('/login')

  # check if there is errors 
  if form.errors:
    for err_msg in form.errors.values():
      flash(f'bad entry: {err_msg[0]}', category='danger')
    return redirect('/login')
    
  return render_template("auth/login.html", form=form)


@auth.route('/sign-up', methods=['GET', 'POST'])
def signUp():
  print("in the sign up function")
  form = SignUpForm()                                  #fetching the data from thr form 
  if form.validate_on_submit():                        #validate the input and create a new user on submit
    flash(" You have signed up successfully, Welcom!", category=createUser(form.username.data, form.email.data, form.password.data))
    create_user_session(form.email.data)
    return redirect('/profile')
     
  # check if there is errors 
  if form.errors:
    for err_msg in form.errors.values():
      flash(f'bad entry: {err_msg[0]}', category='danger')
    return redirect('/sign-up')

  return render_template("auth/sign-up.html", form=form)

#loggin out
@auth.route('/logout')
def logout():
  end_user_session()

  return redirect('/login')
  


@auth.route('/profile', methods=['GET', 'POST'])
def profile_page():
  form = ProfileForm('customer')
  if form.validate_on_submit():                     #validate the form then update it
    flash(' Your data has been updated successfully ', category=update_user(session['customer_id'], form, 'customer'))
    #fill the form with new values

    return redirect(url_for('auth.profile_page'))
  #populate the form with new data
  if session.get("customer_name"):
    print('update the session -----------------------', session.get("customer_name"))
    form.profile_username.data = session['customer_name']
    form.profile_email.data = session['customer_email']
    form.profile_dob.data = session['customer_dob']
    form.profile_ssn.data = session['customer_ssn']
    form.profile_phone.data = session['customer_phone']
    # return redirect(url_for('auth.profile_page'))

  if form.errors:
    for err_msg in form.errors.values():
      flash(f'bad entry: {err_msg[0]}', category='danger')
    return redirect(url_for('auth.profile_page'))

  return render_template("auth/profile.html", form=form)


@auth.route('/dependents/')
def dependents_page():
  
  return render_template("auth/dependents.html", dependents=access_user_dependents(session['customer_id']) )


@auth.route('/dependents/<dependent_id>', methods=['GET', 'POST'])
def dependent_form(dependent_id):
  form = ProfileForm('dependent')
  # check on submitting and create new dependent
  if form.validate_on_submit() and dependent_id == 'add_dependent':                    
    flash(' You have added a dependent ', category=create_dep_for_user(form, session['customer_id']))
    return redirect(url_for('auth.dependents_page'))

  #showing dependent data and and check on submit to update
  if dependent_id != 'add_dependent':
     # check on submitting and update the data 
    if form.validate_on_submit() and dependent_id != 'add_dependent': 
      flash(" You have updated the information of your dependent", category=update_dependent(dependent_id, form))
      return redirect(url_for('auth.dependent_form', dependent_id=dependent_id))
    #fetch dependent
    info = fetch_data_by(dependent_id, 'dependent', 'dependent_ssn')
    #fil the form with dependent info
    form.profile_username.data = info['dependent_name']
    form.profile_email.data = info['dependent_email']
    form.profile_dob.data = info['dependent_dob']
    form.profile_ssn.data = info['dependent_ssn']
    #fill the form with new values
  return render_template("auth/dependentForm.html", form=form, form_state=dependent_id)


#policies for customer and his dependents
@auth.route('/policies/')
def policies_page():
  print("ddddddddddddddddddddddddddddddddddddddd", access_customer_policies_id( session['customer_id'] ))
  return render_template("auth/policies.html", policies=access_customer_policies_id(session['customer_id']) )

@auth.route('/policies/<policy_id>', methods=['GET', 'POST'], defaults={'info': None,  'plan': None, 'associated_hospitals': None})
def policy_form(policy_id, info, associated_hospitals, plan):
  form = PolicyForm()
  # print('sssssssssssssssssssssssssss', fetch_availble_ssn(session['customer_id'], session['customer_ssn'], session['customer_name']))
  form.policy_beneficiary_ssn.choices = fetch_availble_ssn(session['customer_id'], session['customer_ssn'], session['customer_name'])
  form.policy_plan.choices = formatted_fetch_all_plans()
  # policy_beneficiary_ssn = fetch_availble_ssn(session['customer_id'])
  # check on submitting and create new dependent
  if form.validate_on_submit() and policy_id == 'add_policy':                    
    flash(' You have added a policy_id ', category=create_policy(form, session['customer_id'], policy_id))
    return redirect(url_for('auth.policies_page'))

  #showing dependent data and and check on submit to update
  if policy_id != 'add_policy':
     # check on submitting and update the data 
    # if form.validate_on_submit() and policy_id != 'add_policy': 
    #   flash(" You have updated the information of your dependent", category=update_dependent(dependent_id, form))
    #   return redirect(url_for('auth.dependent_form', dependent_id=dependent_id))
    #fetch dependent
    info = fetch_data_by(policy_id, 'policy', 'policy_id')
    plan = fetch_associated_plan(policy_id)
    associated_hospitals = fetch_plan_hopitals(plan['plan_id'])
    #fil the form with dependent info
    form.policy_beneficiary_ssn.data = info['policy_beneficiary_ssn']
    # form.profile_email.data = info['dependent_email']
    # form.profile_dob.data = info['dependent_dob']
    # form.profile_ssn.data = info['dependent_ssn']
    #fill the form with new values
  return render_template("auth/policyForm.html", form=form, form_state=policy_id, info=info, plan=plan, hospitals=associated_hospitals)

@auth.route('/claims/')
def claims_page():
  policies = access_customer_policies_id(session['customer_id'])
  print('qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqtttttt',policies )
  policyId_ssn_name_tuple_list = []
  for policy_id, ssn, date in policies:
    policyId_ssn_name_tuple_list.append((policy_id, ssn, fetch_name_for_ssn(ssn)))

  return render_template("auth/claims.html", policies=policyId_ssn_name_tuple_list )



@auth.route('/claims/<policy_id>/<policy_beneficiry>', methods=['GET', 'POST'])
def claim_form(policy_id, policy_beneficiry):
  form = ClaimForm()
  form.claim_beneficiary_name.data = policy_beneficiry
  form.claim_hospital_name.choices = fetch_claim_hopitals(policy_id)
  
  if form.validate_on_submit():
    flash('You have issued a claim', category=create_claim(form, policy_id))

    return redirect(url_for('auth.claims_page'))
  return render_template("auth/claimForm.html", form=form)



@auth.route('/admin', methods=['GET', 'POST'])
def admin():
  form = LoginForm('admin')
  if form.validate_on_submit():                             #validate and check for the right credentials                                                               
    hash_to_check = fetch_user_hash(form.email.data, 'admin')        #fetch the hash related to the email (correct password)
    if check_hash(hash_to_check, form.password.data):
      flash('You are Logged in', category='success')
      create_user_session(form.email.data, 'admin')
      return  redirect(url_for('auth.admin_profile'))
    else:
      flash('Wrong Credential!', category='danger')
      return redirect('/admin')

  # check if there is errors 
  if form.errors:
    for err_msg in form.errors.values():
      flash(f'bad entry: {err_msg[0]}', category='danger')
    return redirect('/admin')

  # return '<h1>this is the admin page<h1>'
  return render_template("auth/admin.html", form=form)


@auth.route('/admin-profile', methods=['GET', 'POST'])
def admin_profile():
  form = ProfileForm('admin')
  if form.validate_on_submit():                     #validate the form then update it
    flash(' Your data has been updated successfully ', category=update_user(session['admin_id'], form, 'admin'))
    #fill the form with new values

    return redirect(url_for('auth.admin_profile'))
  #populate the form with new data
  if session.get("admin_name"):
    print('update the session -----------------------', session.get("admin_name"))
    form.profile_username.data = session['admin_name']
    form.profile_email.data = session['admin_email']
    form.profile_dob.data = session['admin_dob']
    form.profile_ssn.data = session['admin_ssn']
    form.profile_phone.data = session['admin_phone']
    # return redirect(url_for('auth.profile_page'))

  if form.errors:
    for err_msg in form.errors.values():
      flash(f'bad entry: {err_msg[0]}', category='danger')

app/views.py
from flask import Blueprint, render_template

from .helpers import access_plans

views = Blueprint('views', __name__)

@views.route('/')
def home():
  return render_template("home.html", plans=access_plans())

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" /> 
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <!-- static CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>{% block title %} base {% endblock %}</title>
  </head>
  <bode>
    <!-- nav bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('views.home') }}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav"> -->
            
              {% if session.get('customer_name') is none and session.get('admin_name') is none %}
                <a class="nav-link" href="{{ url_for('auth.login') }}">login</a>
                <a class="nav-link" href="{{ url_for('auth.signUp') }}">sign-up</a>
                <a class="nav-link" href="{{ url_for('auth.admin') }}">admin</a>
              {% elif session.get('customer_name') != none %}
                <a class="nav-link" href="{{ url_for('auth.logout') }}">logout</a>
                <a class="nav-link" href="{{ url_for('auth.profile_page') }}">hi {{session['customer_name']}}</a>
              {% elif session.get('admin_name') != none %}
                <a class="nav-link" href="{{ url_for('auth.logout') }}">logout</a>
                <a class="nav-link" href="{{ url_for('auth.admin_profile') }}">hi {{session['admin_name']}}</a>
              {% endif %}
          
          </div>
        </div>
      </div>
    </nav>

    <!-- checking for form errors -->
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for categories, msg in messages %}
          <div class="alert alert-{{ categories }} text-center" role="alert">
            {{ msg }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}    

    {% block content %}
      content
    {% endblock %}
    
  <!-- footer -->
  <footer class="py-5 bg-dark">
    <div class="container px-5"><p class="m-0 text-center text-white">Copyright © Your Website 2021</p></div>
  </footer> 
      
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </bode>
</html>

app/templates/home.html
{% extends "base.html" %}
{% block title %} home {% endblock %}
{% block content %}
  <header class="py-5" style="background-color: #6f42c1;">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div class="text-center my-5">
                    <h1 class="display-5 fw-bolder text-white mb-2">The greatest health insurance company ever</h1>
                </div>
            </div>
        </div>
    </div>
  </header>

  <!-- planes -->
  <section class="bg-light py-5 border-bottom">
    <div class="container px-5 my-5">
        <div class="text-center mb-5">
            <h2 class="fw-bolder">Pay as you grow</h2>
            <p class="lead mb-0">With our no hassle pricing plans</p>
        </div>
        <div class="row gx-5 justify-content-center">
            
            <div class="row gx-5 justify-content-center">
                <!-- Pricing card free-->
                {% for plan in plans %}
                    <div class="col-lg-6 col-xl-4 mt-5">
                        <div class="card mb-5 mb-xl-0">
                            <div class="card-body p-5">
                                <div class="mb-3">
                                    <!-- plan name -->
                                    <span class="display-4 fw-bold">{{ plan[1] }}</span>
                                </div>
                                <div class="mb-3">
                                  <span class="display-4 fw-bold">${{ plan[3] }}</span>
                                  <span class="text-muted">/ mo.</span>
                                </div>
                                <ul class="list-unstyled mb-4">
                                    <li class="mb-2">
                                        <!-- plan price -->
                                        <i class="bi bi-check text-primary"></i>
                                        Coverage: {{ plan[2] }}
                                    </li>
                                </ul>
                                <div class="d-grid"><a class="btn btn-outline-primary" href="{{ url_for('auth.plan_form', plan_id=plan[0]) }}">SHOW INFO</a></div>
                            </div>
                        </div>
                    </div>        
                {% endfor %}
            </div>           
        </div>
    </div>
    
  </section>

{% endblock %}